language: php

php:
  - '5.6'
  - '7.0'
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - composer dumpautoload

script:
  - vendor/phpunit/phpunit/phpunit tests
